from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any, Protocol

import requests


@dataclass
class AIResult:
    ok: bool
    text: str
    provider: str
    model: str
    error: str | None = None


class AIProvider(Protocol):
    name: str
    model: str

    def complete(self, system_prompt: str, user_prompt: str, context: dict[str, Any] | None = None) -> AIResult:
        ...


class FallbackProvider:
    name = "fallback"
    model = "deterministic"

    def complete(self, system_prompt: str, user_prompt: str, context: dict[str, Any] | None = None) -> AIResult:
        return AIResult(
            ok=False,
            text="Praetor AI is unavailable, so this response was generated by deterministic fallback logic.",
            provider=self.name,
            model=self.model,
            error="AI provider unavailable",
        )


class OpenAIProvider:
    name = "openai"

    def __init__(self, api_key: str, model: str, timeout: int = 25):
        self.api_key = api_key
        self.model = model
        self.timeout = timeout

    def complete(self, system_prompt: str, user_prompt: str, context: dict[str, Any] | None = None) -> AIResult:
        try:
            payload = {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "temperature": 0.25,
            }
            response = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=self.timeout,
            )
            if response.status_code >= 400:
                return AIResult(
                    ok=False,
                    text="Praetor AI is unavailable. Deterministic fallback should be used.",
                    provider=self.name,
                    model=self.model,
                    error=f"OpenAI {response.status_code}: {response.text[:240]}",
                )
            data = response.json()
            text = (((data.get("choices") or [{}])[0].get("message") or {}).get("content") or "").strip()
            if not text:
                return AIResult(
                    ok=False,
                    text="Praetor AI returned an empty response. Deterministic fallback should be used.",
                    provider=self.name,
                    model=self.model,
                    error="Empty AI response",
                )
            return AIResult(ok=True, text=text, provider=self.name, model=self.model)
        except requests.RequestException as e:
            return AIResult(
                ok=False,
                text="Praetor AI request failed. Deterministic fallback should be used.",
                provider=self.name,
                model=self.model,
                error=f"{type(e).__name__}: {str(e)[:240]}",
            )


def get_ai_provider() -> AIProvider:
    api_key = (os.getenv("OPENAI_API_KEY") or "").strip()
    model = (os.getenv("OPENAI_MODEL") or "gpt-4o-mini").strip()
    if not api_key:
        return FallbackProvider()
    return OpenAIProvider(api_key=api_key, model=model)


def ai_provider_status() -> dict[str, Any]:
    api_key = (os.getenv("OPENAI_API_KEY") or "").strip()
    model = (os.getenv("OPENAI_MODEL") or "gpt-4o-mini").strip()
    openai_configured = bool(api_key)
    return {
        "provider": "openai" if openai_configured else "fallback",
        "model": model if openai_configured else "deterministic",
        "openai_configured": openai_configured,
        "fallback_mode": not openai_configured,
    }
